const $=id=>document.getElementById(id);
function yaml(){
 const n=$("name").value,v=$("version").value,b=$("base").value,p=$("path").value,m=$("method").value,d=$("desc").value;
 return "openapi: 3.0.3\ninfo:\n  title: "+n+"\n  version: "+v+"\n  description: Generated by NexTerm API Studio\nservers:\n  - url: https://example.com"+b+"\npaths:\n  "+p+":\n    "+m.toLowerCase()+":\n      summary: "+d+"\n      responses:\n        '200':\n          description: Success\n";
}
function render(){$("yaml").textContent=yaml();$("status").textContent="Generated"}
$("generate").onclick=render;
$("example").onclick=()=>{$("name").value="NexTerm API";$("version").value="1.0.0";$("base").value="/api/v1";$("path").value="/sessions";$("method").value="POST";$("desc").value="Create a terminal session";render()};
$("copy").onclick=async()=>{await navigator.clipboard.writeText($("yaml").textContent);$("status").textContent="Copied"};
$("download").onclick=()=>{const blob=new Blob([yaml()],{type:"text/yaml"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="openapi.yaml";a.click();URL.revokeObjectURL(a.href)};
render();